### ISSUE TITLE
name 'read_excel' is not defined.

### ISSUE THREAD

**Issue by lilymc03** [mwermelinger/Learn-to-code-for-data-analysis#11]
I was working through exercise six of the first notebook when I ran into this error. 
![image](https://user-images.githubusercontent.com/72659666/95657243-57c4e780-0b0b-11eb-8c0a-c5a34de37336.png)

I thought it may have something to do with UTF-8 encoding mentioned earlier in the course, so I tried redownloading the excel files to no avail. 

![image](https://user-images.githubusercontent.com/72659666/95657262-732ff280-0b0b-11eb-82f8-7f3cdaf72828.png)

The file names are correct, so I'm not sure what is causing this issue.

**Comment by mwermelinger** [comment]
The error message isn't complaining about the file names, it says that `read_excel` is undefined. This means that, in your current work session, you haven't run the cell that imports pandas.
