### ISSUE TITLE
Week 4 'datetime' issue

### ISSUE THREAD

**Issue by Fitz0202** [mwermelinger/Learn-to-code-for-data-analysis#4]
Hi

I'm working through the Learn to Code for Data Analysis course and am experiencing an issue in week 4 and wonder if anyone could help. 

I have been through the various stages of the notebook and changed the value types of the columns so everything is correct and the 'GMT' column values are datetime64[NS]. However the line of code which follows (In [40] which was already in the notebook) returns a NameError saying "name 'datetime' is not defined".

![Issue1](https://user-images.githubusercontent.com/64598182/80724787-25de3c80-8afa-11ea-92a1-7234f533d674.PNG)

Also, subsequent lines with 'datetime' in the code also return NameError. This is stopping me progressing through the course and completing the mandatory week 4 quiz.

Being a complete beginner I obviously don't have the knowledge to navigate my way out of this and I would greatly appreciate your help.

Thanks

**Comment by LauraGuest** [comment]
I'm experiencing the same issue. Have you been able to find away around the error?

**Comment by Fitz0202** [comment]
Hi, yes I have. I researched online and found the answer after hours
thinking I couldn't complete the course.

You need to type the following code after re indexing:

From datetime import datetime

Hope this helps.

Chris

**Comment by mwermelinger** [comment]
[Section 1.4 of Week 4](https://www.open.edu/openlearn/ocw/mod/oucontent/view.php?id=83247&section=1.4) shows and explains the `from datetime import datetime` statement but we forgot to put the corresponding code in the exercises notebook. Sorry about that and thanks for reporting it. Will fix.
