### ISSUE TITLE
Notebook won't open, JSON error

### ISSUE THREAD

**Issue by lolob156** [mwermelinger/Learn-to-code-for-data-analysis#7]
Hi, somehow the notebook for exercise 1 doesn't open and trying always gives a notJSON error. What can I do?

**Comment by mwermelinger** [comment]
That's strange. I just downloaded the notebooks from GitHub, opened Exercises_1.ipynb with Anaconda 2020.02 (which was released in March and has Python 3.7.6, Python 7.12.0 and Jupyter 6.0.3) and everything's fine. My guess is that your file somehow got corrupted. Try downloading again.

**Comment by lolob156** [comment]
Yeah, I think that's the most obvious thing to try and I had done this several times before I reported the issue ;) Still same thing...any other idea?? Thanks in advance

**Comment by lolob156** [comment]
And before you ask, I have also restarted my computer and reopened the anaconda navigator. Still the same error....

**Comment by lolob156** [comment]
Update: I have uninstalled everything and now reinstalled it and now it works. Odd. But it's fine now ;)

**Comment by mwermelinger** [comment]
Sounds like some subtle software incompatibility issues that led to the notebook format not being properly understood. Glad you persevered and resolved it. Enjoy the course!

**Comment by gilleth** [comment]
I am having the same issue! I am using Windows 11 and anaconda and have installed and uninstalled numerous times but still the same JSON error. Anything else I can try?
